language: node_js

node_js:
  - "0.10"
  - "iojs-v1.0.4"

sudo: false

cache:
  directories:
    - node_modules

env:
  - DB=mysql DIALECT=mysql
  # - DB=mysql DIALECT=postgres
  # - DB=mysql DIALECT=postgres-native
  # - DB=mysql DIALECT=sqlite
  # - DB=mysql DIALECT=mariadb
  # - DB=mysql DIALECT=mssql

addons:
  postgresql: "9.3"

before_install:
  - (curl https://raw.githubusercontent.com/creationix/nvm/v0.23.2/install.sh | bash) || true

before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"

script:
  - "make test"

branches:
  only:
    - master
    - 1.7.0
    - iojs

matrix:
  fast_finish: true
  include:
    - node_js: "0.10"
      env: COVERAGE=true
  allow_failures:
    - node_js: "0.10"
      env: COVERAGE=true
